## See https://github.com/metacran/r-builder for details.

language: r	 
sudo: required
cache: packages	
dist: trusty

r_github_packages:
  - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - Rscript -e 'covr::codecov()'
